/// <reference path="../../src/API/Player/Player.h" />

import { Vec3 } from "../Math/Vec3";
import { Agent } from "../Actor/Agent";
import { LayeredAbilities } from "./LayeredAbilities";
import { Container } from "../Container/Container";
import { ItemStack } from "../Item/ItemStack";
import { GameMode } from "./GameMode";
import { ActorUniqueID } from "../Actor/ActorUniqueID";

declare class PlayerClass {
    xuid: string | undefined;
    uuid: string | undefined;
    realName: string | undefined;
    name: string | undefined;
    IPAndPort: string | undefined;
    localeCode: string | undefined;
    shadowRadius: number | undefined;
    speed: number | undefined;
    userId: number | undefined;
    itemUseDuration: number | undefined;
    itemUseStartupProgress: number | undefined;
    itemUseIntervalProgress: number | undefined;
    maxChunkBuildRadius: number | undefined;
    blockedUsingDamagedShieldTimeStamp: number | undefined;
    blockedUsingShieldTimeStamp: number | undefined;
    blockingStartTimeStamp: number | undefined;
    chunkRadius: number | undefined;
    direction: number | undefined;
    enchantmentSeed: number | undefined;
    luck: number | undefined;
    mapIndex: number | undefined;
    maxItemCooldownLeft: number | undefined;
    interactText: string | undefined;
    playerIndex: number | undefined;
    playerLevel: number | undefined;
    selectedItemSlot: number | undefined;
    playerSessionId: string;
    platformOnlineId: string;
    serverId: string | undefined;
    sleepRotation: number | undefined;
    usedPotion: number | undefined;
    xpEarnedAtCurrentLevel: number | undefined;
    xpNeededForNextLevel: number | undefined;
    isLoading: boolean | undefined;
    isPlayerInitialized: boolean | undefined;
    isImmobile: boolean | undefined;
    isSleeping: boolean | undefined;
    isTeacher: boolean | undefined;
    isSimulated: boolean | undefined;
    isFireImmune: boolean | undefined;
    isInTrialMode: boolean | undefined;
    isBlocking: boolean | undefined;
    isSilentObserver: boolean | undefined;
    isEmoting: boolean | undefined;
    isFlying: boolean | undefined;
    isForcedRespawn: boolean | undefined;
    isHostingPlayer: boolean | undefined;
    isHungry: boolean | undefined;
    isHurt: boolean | undefined;
    isInRaid: boolean | undefined;
    isRespawningFromTheEnd: boolean | undefined;
    isSleepingLongEnough: boolean | undefined;
    isSpawned: boolean | undefined;
    isUsingItem: boolean | undefined;
    isValidSpawn: boolean | undefined;
    canStartSleepInBed: boolean | undefined;
    canExistWhenDisallowMob: boolean | undefined;
    canFreeze: boolean | undefined;
    canChangeDimensionsUsingPortal: boolean | undefined;
    canInteractWithOtherEntitiesInGame: boolean | undefined;
    canObstructSpawningAndBlockPlacement: boolean | undefined;
    canBeSeenOnMap: boolean | undefined;
    canJump: boolean | undefined;
    canOpenContainerScreen: boolean | undefined;
    canSleep: boolean | undefined;
    canUseOperatorBlocks: boolean | undefined;
    hasDiedBefore: boolean | undefined;
    hasBedPosition: boolean | undefined;
    hasOpenContainer: boolean | undefined;
    hasOwnedChunkSource: boolean | undefined;
    hasRespawnAnchorPosition: boolean | undefined;
    hasRespawnPosition: boolean | undefined;

    disconnect: () => boolean | undefined;
    sendMessage: () => boolean | undefined;
    setAbility: () => boolean | undefined;
    addAndRefresh: () => boolean | undefined;
    broadcastPlayerSpawnedMobEvent: () => void;
    canUseAbility: () => boolean | undefined;
    causeFoodExhaustion: () => boolean | undefined;
    checkBed: () => boolean | undefined;
    checkNeedAutoJump: () => boolean | undefined;
    checkSpawnBlock: () => boolean | undefined;
    clearRespawnPosition: () => boolean | undefined;
    completeUsingItem: () => boolean | undefined;
    eat: () => boolean | undefined;
    equippedArmorItemCanBeMoved: () => boolean | undefined;
    fireDimensionChangedEvent: () => any;// TODO
    forceAllowEating: () => boolean;
    getAbilities: () => LayeredAbilities | undefined;
    getAgent: () => Agent | undefined;
    getAgentID: () => ActorUniqueID | undefined; // TODO
    getAgentIfAllowed: () => Agent | undefined;
    getBedPosition: () => any;
    getCapePos: () => Vec3 | undefined;
    getContainerManager: () => any;
    getContainerRegistryAccess: () => any;
    getContainerRegistryTracker: () => any;
    getCurrentActiveShield: () => ItemStack | undefined;
    getDestroyProgress: () => any;
    getDynamicContainerSerialization: () => any;
    getExpectedSpawnDimensionId: () => any;
    getGameMode: () => GameMode | undefined;
    getInventory: () => Container | undefined;
    getItemCooldownLeft: () => number;
    getItemInUse: () => ItemStack | undefined;
    getPlatform: () => any;
    getItemStackNetManager: () => any;
    getPlayerGameType: () => any;
    getPlayerPermissionLevel: () => any;
    getPlayerUIItem: () => any;
    getRespawnAnchorPosition: () => any;
    getSelectedItem: () => ItemStack | undefined;
    getSkin: () => any;
    getSpawnDimension: () => any;
    getSpawnPosition: () => any;
    getSupplies: () => any;
    getTrackedBosses: () => ActorUniqueID[] | undefined;
    getXpNeededForLevelRange: () => number | undefined;
    hasOpenContainerOfContainerType: () => any;
    hasResource: () => any;
    interact: () => boolean | undefined;
    inventoryChanged: () => void;
    is2DPositionRelevant: () => any;
    isHiddenFrom: () => any;
    isItemOnCooldown: () => any;
    passengerCheckMovementStats: () => boolean | undefined;
    playPredictiveSynchronizedSound: () => void;
    recheckRespawnPosition: () => void | undefined;
    registerTrackedBoss: () => void;
    releaseUsingItem: () => boolean | undefined;
    resendAllChunks: () => boolean | undefined;
    resetPlayerLevel: () => boolean | undefined;
    resetPublisherInitialSpawn: () => boolean | undefined;
    resetToDefaultGameMode: () => boolean | undefined;
    saveLastDeathLocation: () => boolean | undefined;
    sendEventPacket: () => boolean | undefined;
    sendPlayerTeleported: () => boolean | undefined;
    sendSpawnExperienceOrbPacketToServer: () => boolean | undefined;
    setAgent: () => boolean | undefined;
    setBedRespawnPosition: () => boolean | undefined;
    setBlockRespawnUntilClientMessage: () => boolean | undefined;
    setChunkRadius: () => boolean | undefined;
    setContainerManagerModel: () => boolean;
    setCursorSelectedItem: () => boolean | undefined;
    setCursorSelectedItemGroup: () => boolean | undefined;
    setEmotingStatus: () => boolean | undefined;
    setEnchantmentSeed: () => boolean | undefined;
    setHasDied: () => boolean | undefined;
    setHasSeenCredits: () => boolean | undefined;
    setInventoryOptions: () => boolean | undefined;
    setLastDeathDimension: () => boolean | undefined;
    setLastDeathPos: () => boolean | undefined;
    setMapIndex: () => boolean | undefined;
    setName: () => boolean | undefined;
    setPermissions: () => boolean | undefined;
    setPlatformOnlineId: () => boolean | undefined;
    setPlayerIndex: () => boolean | undefined;
    setPlayerUIItem: () => boolean | undefined;
    setRespawnPosition: () => boolean | undefined;
    setRespawnPositionCandidate: () => boolean | undefined;
    setRespawnReady: () => boolean | undefined;
    setSelectedItem: () => boolean | undefined;
    setSelectedSlot: () => any;
    setSpawnBlockRespawnPosition: () => any;
    setUsedPotion: () => boolean | undefined;
    shouldShowCredits: () => boolean | undefined;
    startCooldown: () => any;
    startDestroying: () => boolean | undefined;
    startItemUseOn: () => any;
    startUsingItem: () => any | undefined;
    stopDestroying: () => boolean | undefined;
    stopGliding: () => boolean | undefined;
    stopItemUseOn: () => boolean | undefined;
    stopUsingItem: () => boolean | undefined;
    take: () => any;
    tickArmor: () => boolean | undefined;
    tryDisableShield: () => boolean | undefined;
    tryStartGliding: () => boolean | undefined;
    tryStartSleeping: () => boolean | undefined;
    unRegisterTrackedBoss: () => any;
    updateBlockSourceTick: () => boolean | undefined;
    updateInventoryTransactions: () => boolean | undefined;
    updateSkin: () => boolean | undefined;
    updateTouch: () => boolean | undefined;
    updateTrackedBosses: () => boolean | undefined;
    useSelectedItem: () => any;

    static checkAndFixSpawnPosition_DEPRECATED: () => any;
    static checkNeedAutoJump: () => any;
    static getCustomHurtSound: () => any;
    static isDangerousVolumeForSpawn: () => any;
    static tryGetFromComponent: () => any;
    static tryGetFromComponentOverload1: () => any;
    static tryGetFromComponentOverload2: () => any;
    static tryGetFromEntity: () => any;
    static updatePlayerGameTypeEntityData: () => any;
}