
#include <ll/api/event/ListenerBase.h>
#include <ll/api/io/LogLevel.h>
#include <ll/api/command/runtime/ParamKind.h>


#include <mc/world/actor/ActionEvent.h>
#include <mc/world/actor/ActorCategory.h>
#include <mc/world/actor/ActorDamageSource.h>
#include <mc/world/actor/ActorDataIDs.h>
#include <mc/world/actor/ActorDefinitionEventType.h>
#include <mc/world/actor/ActorDefinitionGroup.h>
#include <mc/world/actor/ActorDefinitionParseStatus.h>
#include <mc/world/actor/ActorEvent.h>
#include <mc/world/actor/ActorFilterGroup.h>
#include <mc/world/actor/ActorFlags.h>
#include <mc/world/actor/ActorInitializationMethod.h>
#include <mc/world/actor/ActorLinkType.h>
#include <mc/deps/shared_types/legacy/actor/ActorLocation.h>
#include <mc/world/actor/ActorTargetFilter.h>
#include <mc/world/actor/ActorTerrainInterlockData.h>
#include <mc/world/actor/ActorType.h>
#include <mc/world/actor/ActorTypeNamespaceRules.h>
#include <mc/world/actor/ArmorMaterialType.h>
#include <mc/world/actor/ArmorTextureType.h>
#include <mc/world/actor/DataItemType.h>
#include <mc/world/actor/DefinitionEventType.h>
#include <mc/world/actor/HorseInventoryEnum.h>
#include <mc/world/actor/KeyOrNameResult.h>
#include <mc/world/actor/MobSpawnMethod.h>
#include <mc/deps/shared_types/legacy/actor/PaletteColor.h>
#include <mc/comprehensive/ParticleType.h>
#include <mc/world/actor/RenderContextType.h>
#include <mc/world/actor/RenderParam.h>
#include <mc/world/actor/SerializedAbilitiesData.h>
#include <mc/world/actor/SkeletalHierarchyIndex.h>
#include <mc/world/actor/SpawnRuleEnum.h>
#include <mc/world/actor/TravelType.h>
#include <mc/world/actor/TypeExecutingEvent.h>

#include <mc/world/level/block/actor/BlockActorType.h>
#include <mc/world/level/block/BlockRenderLayer.h>
#include <mc/world/level/block/BlockSupportType.h>
// #include <mc/world/level/block/BlockTintType.h>
#include <mc/world/level/block/BlockProperty.h>
#include <mc/world/level/material/MaterialType.h>

#include <mc/world/actor/player/AbilitiesIndex.h>
#include <mc/world/actor/player/AbilitiesLayer.h>
#include <mc/world/actor/player/Ability.h>
#include <mc/world/actor/player/BedSleepingResult.h>
#include <mc/world/actor/player/LoadingState.h>
#include <mc/world/actor/player/Player.h>
#include <mc/world/actor/player/PlayerSpawnFallbackType.h>
#include <mc/world/actor/player/PlayerUISlot.h>
#include <mc/world/actor/player/SkinAdjustments.h>
#include <mc/world/actor/player/TrustedSkinFlag.h>

#include <mc/server/commands\AllowListCommand.h>
#include <mc/server/commands\BlockStateCommandParam.h>
#include <mc/server/commands\ChangeSettingCommand.h>
#include <mc/server/commands\CommandAsyncFlag.h>
#include <mc/server/commands\CommandBlockNameResult.h>
#include <mc/server/commands\CommandCheatFlag.h>
#include <mc/server/commands\CommandCompareOperator.h>
#include <mc/server/commands\CommandEditorFlag.h>
#include <mc/server/commands\CommandExecuteFlag.h>
#include <mc/server/commands\CommandFlag.h>
#include <mc/server/commands\CommandLexer.h>
#include <mc/server/commands\CommandOperator.h>
#include <mc/server/commands\CommandOriginType.h>
#include <mc/server/commands\CommandOutputMessageType.h>
#include <mc/server/commands\CommandOutputParameter.h>
#include <mc/server/commands\CommandOutputType.h>
#include <mc/server/commands\CommandParameterDataType.h>
#include <mc/server/commands\CommandParameterOption.h>
#include <mc/server/commands\CommandPermissionLevel.h>
#include <mc/server/commands\CommandRationalRange.h>
#include <mc/server/commands\CommandRegistry.h>
#include <mc/server/commands\CommandSelectionOrder.h>
#include <mc/server/commands\CommandSelectionType.h>
#include <mc/server/commands\CommandStatus.h>
#include <mc/server/commands\CommandSyncFlag.h>
#include <mc/server/commands\CommandTypeFlag.h>
#include <mc/server/commands\CommandUsageFlag.h>
#include <mc/server/commands\CommandVisibilityFlag.h>
#include <mc/server/commands\CurrentCmdVersion.h>
#include <mc/server/commands\PlayerPermissionLevel.h>
#include <mc/server/commands\SaveCommand.h>
#include <mc/server/commands\SemanticConstraint.h>
#include <mc/server/commands\editor\ProjectCommand.h>
#include <mc/server/commands\edu\AgentCommand.h>
#include <mc/server/commands\edu\CodeBuilderActorInfoCommand.h>
#include <mc/server/commands\edu\CodeBuilderCommand.h>
#include <mc/server/commands\edu\DialogueCommand.h>
#include <mc/server/commands\edu\LessonActionType.h>
#include <mc/server/commands\edu\ResourceUriCommand.h>
#include <mc/server/commands\edu\agent_commands\SubCommand.h>
#include <mc/server/commands\functions\FunctionQueueOrder.h>
#include <mc/server/commands\functions\FunctionState.h>
#include <mc/server/commands\shared\ScriptDebugCommand.h>
#include <mc/server/commands\standard\BossbarCommand.h>
#include <mc/server/commands\standard\CameraAimAssistCommand.h>
#include <mc/server/commands\standard\CameraCommand.h>
#include <mc/server/commands\standard\CloneCommand.h>
#include <mc/server/commands\standard\DamageCommand.h>
#include <mc/server/commands\standard\EffectCommand.h>
#include <mc/server/commands\standard\EventCommand.h>
#include <mc/server/commands\standard\ExecuteCommand.h>
#include <mc/server/commands\standard\FillCommand.h>
#include <mc/server/commands\standard\FogCommand.h>
#include <mc/server/commands\standard\GameTestCommand.h>
#include <mc/server/commands\standard\HudOptions.h>
#include <mc/server/commands\standard\InputPermissionCommand.h>
#include <mc/server/commands\standard\ListDCommand.h>
#include <mc/server/commands\standard\LocateSubcommand.h>
#include <mc/server/commands\standard\LootCommand.h>
#include <mc/server/commands\standard\MusicCommand.h>
#include <mc/server/commands\standard\NewExecuteCommand.h>
#include <mc/server/commands\standard\PermissionCommand.h>
#include <mc/server/commands\standard\PlaceCommand.h>
#include <mc/server/commands\standard\ReloadCommand.h>
#include <mc/server/commands\standard\ReplaceItemCommand.h>
#include <mc/server/commands\standard\RideCommand.h>
#include <mc/server/commands\standard\ScheduleCommand.h>
#include <mc/server/commands\standard\ScoreboardCommand.h>
#include <mc/server/commands\standard\SetBlockCommand.h>
#include <mc/server/commands\standard\StructureActionType.h>
#include <mc/server/commands\standard\TagCommand.h>
#include <mc/server/commands\standard\TeleportAnalysis.h>
#include <mc/server/commands\standard\TestForBlocksCommand.h>
#include <mc/server/commands\standard\TickingAreaCommand.h>
#include <mc/server/commands\standard\TimeCommand.h>
#include <mc/server/commands\standard\TitleCommand.h>
#include <mc/server/commands\standard\TitleRawCommand.h>
#include <mc/server/commands\standard\UnlockRecipeCommand.h>
#include <mc/server/commands\standard\VolumeAreaCommand.h>
#include <mc/server/commands\standard\WeatherCommand.h>
#include <mc/server/commands\standard\locate_command_util\Biomes.h>
// #include <mc/server/commands\test\TestAssetCommandType.h>
// #include <mc/server/commands\test\TestCommandType.h>

#include <mc\common\CompactionStatus.h>
#include <mc\common\FacingID.h>
#include <mc\common\GameUserType.h>
#include <mc\common\GameVersion.h>
#include <mc\common\SubClientId.h>

#include <mc\common\editor\WorldType.h>
#include <mc\legacy\facing\Axis.h>
#include <mc\legacy\facing\Name.h>
#include <mc\legacy\facing\Rotation.h>
#include <mc\common\title_info\TitleId.h>

// #include <mc\world\item\ArmorSlot.h>
#include <mc\world\item\BannerPatternItem.h>
#include <mc\world\item\BucketFillType.h>
#include <mc\world\item\CameraItemComponentLegacy.h>
#include <mc\world\item\CoalItem.h>
#include <mc\world\item\CompoundContainerType.h>
#include <mc\world\item\CompoundType.h>
#include <mc\world\item\CreativeItemCategory.h>
#include <mc\world\item\FertilizerType.h>
#include <mc\world\item\FireworkChargeItem.h>
#include <mc\world\item\FoodItemComponentLegacy.h>
#include <mc\world\item\HandSlot.h>
#include <mc\world\item\HorseArmorItem.h>
#include <mc\world\item\HumanoidArmorItem.h>
#include <mc\world\item\InHandUpdateType.h>
#include <mc\world\item\ItemAcquisitionMethod.h>
#include <mc\world\item\ItemColor.h>
#include <mc\world\item\ItemCommandVisibility.h>
#include <mc\world\item\ItemContextType.h>
#include <mc\world\item\ItemDescriptor.h>
#include <mc\world\item\ItemIconInfoType.h>
#include <mc\world\item\ItemLockMode.h>
#include <mc\world\item\ItemUseMethod.h>
#include <mc\world\item\MapType.h>
#include <mc\world\item\MedicineType.h>
#include <mc\world\item\NotifyItemUsedOnEvent.h>
#include <mc\world\item\PageContent.h>
#include <mc\world\item\Rarity.h>
#include <mc\world\item\SaveContext.h>
// #include <mc\world\item\SlotWithDropChance.h>
#include <mc\world\item\SmithingTemplateItem.h>
#include <mc\world\item\SuspiciousStewItem.h>
#include <mc\world\item\alchemy\Potion.h>
#include <mc\world\item\components\OnUseOrder.h>
#include <mc\world\item\components\RenderOffsetsItemComponent.h>
#include <mc\world\item\components\UseTimeDepletedOrder.h>
#include <mc\world\item\crafting\RecipeUnlockingRequirement.h>
#include <mc\world\item\enchanting\Enchant.h>
#include <mc\world\item\enchanting\EnchantResultType.h>
#include <mc\world\item\enchanting\EquipmentFilter.h>
#include <mc\world\item\registry\ItemVersion.h>

#include <mc\world\inventory\ActorContainerType.h>
#include <mc\world\inventory\InventoryLayout.h>
#include <mc\world\inventory\InventoryLeftTabIndex.h>
#include <mc\world\inventory\InventoryRightTabIndex.h>
#include <mc\world\inventory\network\ItemStackNetManagerServer.h>
#include <mc\world\inventory\network\ItemStackNetResult.h>
#include <mc\world\inventory\network\ItemStackRequestActionHandler.h>
#include <mc\world\inventory\network\ItemStackRequestActionMineBlock.h>
#include <mc\world\inventory\network\ItemStackRequestActionType.h>
#include <mc\world\inventory\network\ItemStackRequestScreen.h>
#include <mc\world\inventory\network\SparseContainerClient.h>
#include <mc\world\inventory\simulation\ContainerScreenActionResultData.h>
#include <mc\world\inventory\simulation\ContainerScreenAutoplaceBehaviour.h>
#include <mc\world\inventory\simulation\ContainerScreenRequestActionType.h>
#include <mc\world\inventory\simulation\ContainerScreenTransferBehaviour.h>
#include <mc\world\inventory\simulation\ContainerValidationCaller.h>
#include <mc\world\inventory\simulation\ContainerValidationCommitObject.h>
#include <mc\world\inventory\simulation\ContainerValidationOperationType.h>
#include <mc\world\inventory\simulation\ContainerValidationOutcome.h>
#include <mc\world\inventory\simulation\SparseContainerBackingSetType.h>
#include <mc\world\inventory\transaction\ComplexInventoryTransaction.h>
#include <mc\world\inventory\transaction\InventorySource.h>
#include <mc\world\inventory\transaction\InventorySourceType.h>
#include <mc\world\inventory\transaction\InventoryTransactionError.h>
#include <mc\world\inventory\transaction\ItemReleaseInventoryTransaction.h>
#include <mc\world\inventory\transaction\ItemUseInventoryTransaction.h>
#include <mc\world\inventory\transaction\ItemUseOnActorInventoryTransaction.h>

#include <mc/network/packet/ModalFormCancelReason.h>
