name: Build

on:
  push:
    paths:
      - xmake.lua
      - src/**
      - patch/**
      - third-party/**
      - .github/workflows/build.yml
  pull_request:
    paths:
      - xmake.lua
      - src/**
      - patch/**
      - third-party/**
      - .github/workflows/build.yml
  workflow_dispatch:

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: ["windows-latest", "Xianyubb","Singl"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/cache@v4
        with:
          path: |
            ~/AppData/Local/.xmake
          key: xmake-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-

      - uses: xmake-io/github-action-setup-xmake@v1
        # with:
        #   xmake-version: branch@master
      - run: |
          git submodule update --init --recursive

      - run: |
          xmake repo -u

      - run: |
          xmake f -a x64 -m release -v -y

      - run: |
          xmake -v -y

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-x64-${{ github.sha }}
          path: |
            bin/
      - name: Download depends
        run: |
          curl -o bin-windows.zip -L https://github.com/IceBlcokMC/node/releases/download/v23.5.0/bin-windows.zip
          curl -o node_modules.zip -L https://github.com/IceBlcokMC/node/releases/download/v23.5.0/node_modules.zip

      - name: Unzip depends
        run: |
          mkdir deps
          mkdir deps/node_modules
          unzip -a -q bin-windows.zip -d deps/
          unzip -a -q node_modules.zip -d deps/node_modules/

      - name: Pack
        run: |
          mkdir full
          mkdir full/plugins

          Copy-Item -Recurse -Force bin/* full/plugins/
          Copy-Item -Recurse -Force -Container deps/node_modules/. full/plugins/Komomo/node_modules/
          cp deps/libnode.dll full/

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-full-x64-${{ github.sha }}
          include-hidden-files: true
          path: |
            full/
