name: Build

on:
  push:
    paths:
      - xmake.lua
      - src/**
      - patch/**
      - third-party/**
      - .github/workflows/build.yml
  pull_request:
    paths:
      - xmake.lua
      - src/**
      - patch/**
      - third-party/**
      - .github/workflows/build.yml
  workflow_dispatch:

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest","Singl"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/cache@v4
        with:
          path: |
            ~/AppData/Local/.xmake
          key: xmake-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-

      - uses: xmake-io/github-action-setup-xmake@v1
        # with:
        #   xmake-version: branch@master
      - run: |
          git submodule update --init --recursive

      - run: |
          xmake repo -u

      - run: |
          xmake f -a x64 -m release -v -y

      - run: |
          xmake -v -y

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.os }}-x64-${{ github.sha }}
          path: |
            bin/

      - name: Download depends
        run: |
          Invoke-WebRequest -Uri "https://github.com/IceBlcokMC/node/releases/download/v22.12.0/bin-windows.zip" -OutFile "bin-windows.zip" -UseBasicParsing
          Invoke-WebRequest -Uri "https://github.com/IceBlcokMC/node/releases/download/v22.12.0/node_modules.zip" -OutFile "node_modules.zip" -UseBasicParsing

      - name: Unzip depends
        run: |
          New-Item -ItemType Directory -Path "deps"
          New-Item -ItemType Directory -Path "deps/node_modules"
          Expand-Archive -Path "bin-windows.zip" -DestinationPath "deps" -Force
          Expand-Archive -Path "node_modules.zip" -DestinationPath "deps/node_modules" -Force

      - name: Pack
        run: |
          New-Item -ItemType Directory -Path "full"
          New-Item -ItemType Directory -Path "full/plugins"

          Copy-Item -Recurse -Force bin\* full\plugins\
          Copy-Item -Recurse -Force -Container deps\node_modules\.\* full\plugins\Komomo\node_modules\
          Copy-Item -Force deps\libnode.dll full\
          Copy-Item -Force deps\node.exe full\

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.os }}-full-x64-${{ github.sha }}
          include-hidden-files: true
          path: |
            full/
